import type { AnimeCard, EpisodeEntry, SeasonInfo } from "./types";

export const MOCK_SEASON_INFO: SeasonInfo = {
  season: "WINTER",
  year: 2026,
  label: "Winter 2026",
};

export const MOCK_ANIME: AnimeCard[] = [
  {
    id: 16498,
    malId: 16498,
    title: "Attack on Titan",
    titleEnglish: "Attack on Titan",
    titleNative: "進撃の巨人",
    cover: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=80",
    color: "#8c5039",
    format: "TV",
    episodes: 25,
    duration: 24,
    status: "FINISHED",
    season: "SPRING",
    seasonYear: 2023,
    averageScore: 90,
    popularity: 580000,
    genres: ["Action", "Drama", "Fantasy", "Mystery"],
    description:
      "Centuries ago, mankind was slaughtered to near extinction by monstrous humanoid creatures called Titans, forcing humans to hide in fear behind enormous concentric walls. What makes these giants truly terrifying is that their taste for human flesh is not born of hunger.",
    startDate: "2013-04-07",
    studio: "WIT Studio",
    trailerSite: "youtube",
    trailerId: "MGRm4IzK1SQ",
    nextAiringEpisode: null,
    nextAiringAt: null,
  },
  {
    id: 101922,
    malId: 38000,
    title: "Demon Slayer: Kimetsu no Yaiba",
    titleEnglish: "Demon Slayer: Kimetsu no Yaiba",
    titleNative: "鬼滅の刃",
    cover: "https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=600&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=1600&auto=format&fit=crop&q=80",
    color: "#c0392b",
    format: "TV",
    episodes: 26,
    duration: 24,
    status: "FINISHED",
    season: "SPRING",
    seasonYear: 2024,
    averageScore: 88,
    popularity: 510000,
    genres: ["Action", "Fantasy", "Supernatural"],
    description:
      "Ever since the death of his father, the burden of supporting the family has fallen upon Tanjiro Kamado's shoulders. One day, he returns home to find his family slaughtered and his sister turned into a demon.",
    startDate: "2019-04-06",
    studio: "ufotable",
    trailerSite: "youtube",
    trailerId: "VQGCKyvzIM4",
    nextAiringEpisode: null,
    nextAiringAt: null,
  },
  {
    id: 113415,
    malId: 40748,
    title: "Jujutsu Kaisen",
    titleEnglish: "JUJUTSU KAISEN",
    titleNative: "呪術廻戦",
    cover: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80",
    color: "#2980b9",
    format: "TV",
    episodes: 24,
    duration: 24,
    status: "FINISHED",
    season: "FALL",
    seasonYear: 2020,
    averageScore: 87,
    popularity: 450000,
    genres: ["Action", "Fantasy", "Supernatural"],
    description:
      "Idly indulging in paranormal activities with the Occult Club, high schooler Yuji Itadori swallows a cursed talisman—the finger of Sukuna, the King of Curses—and is thrust into the world of Jujutsu Sorcerers.",
    startDate: "2020-10-03",
    studio: "MAPPA",
    trailerSite: "youtube",
    trailerId: "4A_X-Dvl0ws",
    nextAiringEpisode: null,
    nextAiringAt: null,
  },
  {
    id: 21,
    malId: 21,
    title: "One Piece",
    titleEnglish: "One Piece",
    titleNative: "ONE PIECE",
    cover: "https://images.unsplash.com/photo-1569701813229-33284b643e3c?w=600&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&auto=format&fit=crop&q=80",
    color: "#f1c40f",
    format: "TV",
    episodes: 1120,
    duration: 24,
    status: "RELEASING",
    season: "FALL",
    seasonYear: 2025,
    averageScore: 89,
    popularity: 420000,
    genres: ["Action", "Adventure", "Comedy", "Fantasy"],
    description:
      "Barely surviving in a barrel after passing through a terrible whirlpool at sea, carefree Monkey D. Luffy ends up aboard a ship under attack by pirates, determined to find the One Piece and become King of the Pirates.",
    startDate: "1999-10-20",
    studio: "Toei Animation",
    trailerSite: "youtube",
    trailerId: "S8_YwFLCh4U",
    nextAiringEpisode: 1121,
    nextAiringAt: 1735000000,
  },
  {
    id: 140960,
    malId: 50265,
    title: "Spy x Family",
    titleEnglish: "SPY x FAMILY",
    titleNative: "SPY×FAMILY",
    cover: "https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1511447333015-45b65e60f6d5?w=1600&auto=format&fit=crop&q=80",
    color: "#27ae60",
    format: "TV",
    episodes: 25,
    duration: 24,
    status: "FINISHED",
    season: "SPRING",
    seasonYear: 2024,
    averageScore: 86,
    popularity: 390000,
    genres: ["Action", "Comedy"],
    description:
      "Corrupt politicians, frenzied nationalists, and other warmongering forces constantly jeopardize the thin veneer of peace. World-class spy Twilight adopts an esper daughter and marries an assassin without knowing their secrets.",
    startDate: "2022-04-09",
    studio: "WIT Studio & CloverWorks",
    trailerSite: "youtube",
    trailerId: "ofXigq9aIpo",
    nextAiringEpisode: null,
    nextAiringAt: null,
  },
  {
    id: 142838,
    malId: 50602,
    title: "Chainsaw Man",
    titleEnglish: "Chainsaw Man",
    titleNative: "チェンソーマン",
    cover: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=600&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=80",
    color: "#e67e22",
    format: "TV",
    episodes: 12,
    duration: 24,
    status: "FINISHED",
    season: "FALL",
    seasonYear: 2024,
    averageScore: 87,
    popularity: 380000,
    genres: ["Action", "Comedy", "Drama", "Supernatural"],
    description:
      "Denji is a young man living in extreme poverty, paying off his deceased father's debt to the yakuza by harvesting devil corpses alongside Pochita, the Chainsaw Devil.",
    startDate: "2022-10-12",
    studio: "MAPPA",
    trailerSite: "youtube",
    trailerId: "jk7KQp3aX9g",
    nextAiringEpisode: null,
    nextAiringAt: null,
  },
  {
    id: 154587,
    malId: 52991,
    title: "Frieren: Beyond Journey's End",
    titleEnglish: "Frieren: Beyond Journey's End",
    titleNative: "葬送のフリーレン",
    cover: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1600&auto=format&fit=crop&q=80",
    color: "#68b0ab",
    format: "TV",
    episodes: 28,
    duration: 24,
    status: "FINISHED",
    season: "FALL",
    seasonYear: 2025,
    averageScore: 94,
    popularity: 290000,
    genres: ["Adventure", "Drama", "Fantasy"],
    description:
      "The demon king has been defeated, and the victorious hero party returns home before disbanding. The four—mage Frieren, hero Himmel, priest Heiter, and warrior Eisen—reminisce about their decade-long journey. But the passing of time is different for elves.",
    startDate: "2023-09-29",
    studio: "Madhouse",
    trailerSite: "youtube",
    trailerId: "qgQunxD0qMo",
    nextAiringEpisode: null,
    nextAiringAt: null,
  },
  {
    id: 151807,
    malId: 52299,
    title: "Solo Leveling",
    titleEnglish: "Solo Leveling",
    titleNative: "俺だけレベルアップな件",
    cover: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80",
    color: "#3047ec",
    format: "TV",
    episodes: 12,
    duration: 24,
    status: "FINISHED",
    season: "WINTER",
    seasonYear: 2026,
    averageScore: 86,
    popularity: 310000,
    genres: ["Action", "Adventure", "Fantasy"],
    description:
      "They say whatever doesn't kill you makes you stronger, but that's not the case for Sung Jinwoo. After being slaughtered by monsters in a high-ranking dungeon, Jinwoo awakens with the mysterious System.",
    startDate: "2024-01-07",
    studio: "A-1 Pictures",
    trailerSite: "youtube",
    trailerId: "w_R7yD8w6hM",
    nextAiringEpisode: null,
    nextAiringAt: null,
  },
  {
    id: 166240,
    malId: 54744,
    title: "Dandadan",
    titleEnglish: "DAN DA DAN",
    titleNative: "ダンダダン",
    cover: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=600&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=80",
    color: "#f39c12",
    format: "TV",
    episodes: 12,
    duration: 24,
    status: "FINISHED",
    season: "FALL",
    seasonYear: 2025,
    averageScore: 87,
    popularity: 240000,
    genres: ["Action", "Comedy", "Sci-Fi", "Supernatural"],
    description:
      "Momo Ayase strikes up an unusual friendship with her school's UFO fanatic, whom she nicknames Okarun. To prove who is right about aliens and ghosts, they make a bet to visit separate occult spots.",
    startDate: "2024-10-04",
    studio: "Science SARU",
    trailerSite: "youtube",
    trailerId: "3eQ2rK8iUaE",
    nextAiringEpisode: null,
    nextAiringAt: null,
  },
  {
    id: 171010,
    malId: 57334,
    title: "Kaiju No. 8",
    titleEnglish: "Kaiju No. 8",
    titleNative: "怪獣8号",
    cover: "https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?w=600&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80",
    color: "#27ae60",
    format: "TV",
    episodes: 12,
    duration: 24,
    status: "FINISHED",
    season: "SPRING",
    seasonYear: 2025,
    averageScore: 84,
    popularity: 220000,
    genres: ["Action", "Sci-Fi"],
    description:
      "With kaiju terrorizing Japan daily, Kafka Hibino works as a sweeper cleaning up remains. But after a strange creature enters his body, Kafka gains the ability to transform into a humanoid kaiju.",
    startDate: "2024-04-13",
    studio: "Production I.G",
    trailerSite: "youtube",
    trailerId: "c3JkG_E1558",
    nextAiringEpisode: null,
    nextAiringAt: null,
  },
  {
    id: 150672,
    malId: 52034,
    title: "Oshi no Ko",
    titleEnglish: "[Oshi No Ko]",
    titleNative: "【推しの子】",
    cover: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1511447333015-45b65e60f6d5?w=1600&auto=format&fit=crop&q=80",
    color: "#9b59b6",
    format: "TV",
    episodes: 11,
    duration: 30,
    status: "FINISHED",
    season: "SPRING",
    seasonYear: 2024,
    averageScore: 87,
    popularity: 310000,
    genres: ["Drama", "Mystery", "Supernatural"],
    description:
      "Sixteen-year-old Ai Hoshino is a talented and beautiful idol adored by her fans. When country doctor Gorou Amemiya is murdered right before delivering her twins, he reincarnates as her newborn son.",
    startDate: "2023-04-12",
    studio: "Doga Kobo",
    trailerSite: "youtube",
    trailerId: "skNmMpUlsrE",
    nextAiringEpisode: null,
    nextAiringAt: null,
  },
  {
    id: 153518,
    malId: 52701,
    title: "Bleach: Thousand-Year Blood War",
    titleEnglish: "Bleach: Thousand-Year Blood War",
    titleNative: "BLEACH 千年血戦篇",
    cover: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=80",
    color: "#2c3e50",
    format: "TV",
    episodes: 13,
    duration: 24,
    status: "FINISHED",
    season: "FALL",
    seasonYear: 2025,
    averageScore: 90,
    popularity: 280000,
    genres: ["Action", "Adventure", "Fantasy", "Supernatural"],
    description:
      "Substitute Soul Reaper Ichigo Kurosaki spends his days fighting against Hollows. When the peace in the Soul Society is shattered by the Wandenreich, Ichigo enters the ultimate battlefield.",
    startDate: "2022-10-11",
    studio: "Pierrot",
    trailerSite: "youtube",
    trailerId: "78WIYzX_Ed8",
    nextAiringEpisode: null,
    nextAiringAt: null,
  },
  {
    id: 160359,
    malId: 54112,
    title: "Blue Lock Season 2",
    titleEnglish: "BLUELOCK Season 2",
    titleNative: "ブルーロック VS. U-20 JAPAN",
    cover: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=600&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=1600&auto=format&fit=crop&q=80",
    color: "#2980b9",
    format: "TV",
    episodes: 14,
    duration: 24,
    status: "RELEASING",
    season: "WINTER",
    seasonYear: 2026,
    averageScore: 81,
    popularity: 205000,
    genres: ["Action", "Drama", "Sports"],
    description:
      "The Blue Lock project moves into its next grueling phase: facing the Japan U-20 team in an all-or-nothing match for the right to represent the nation on the world stage.",
    startDate: "2024-10-05",
    studio: "Eight Bit",
    trailerSite: "youtube",
    trailerId: "w_R7yD8w6hM",
    nextAiringEpisode: 12,
    nextAiringAt: 1735000000,
  },
  {
    id: 171627,
    malId: 57555,
    title: "Re:ZERO Season 3",
    titleEnglish: "Re:ZERO -Starting Life in Another World- Season 3",
    titleNative: "Re:ゼロから始める異世界生活 3rd season",
    cover: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1511447333015-45b65e60f6d5?w=1600&auto=format&fit=crop&q=80",
    color: "#8e44ad",
    format: "TV",
    episodes: 16,
    duration: 24,
    status: "RELEASING",
    season: "WINTER",
    seasonYear: 2026,
    averageScore: 88,
    popularity: 270000,
    genres: ["Action", "Adventure", "Drama", "Fantasy", "Psychological"],
    description:
      "A year after the victory in the Sanctuary, Subaru Natsuki and Emilia receive an official invitation to the Watergate City of Pristella, where Sin Archbishops gather to strike.",
    startDate: "2024-10-02",
    studio: "White Fox",
    trailerSite: "youtube",
    trailerId: "O6qVieflwQs",
    nextAiringEpisode: 9,
    nextAiringAt: 1735000000,
  },
  {
    id: 130003,
    malId: 47917,
    title: "BOCCHI THE ROCK!",
    titleEnglish: "BOCCHI THE ROCK!",
    titleNative: "ぼっち・ざ・ろっく！",
    cover: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1600&auto=format&fit=crop&q=80",
    color: "#e84393",
    format: "TV",
    episodes: 12,
    duration: 24,
    status: "FINISHED",
    season: "FALL",
    seasonYear: 2024,
    averageScore: 88,
    popularity: 320000,
    genres: ["Comedy", "Music", "Slice of Life"],
    description:
      "Yearning to make friends and perform live with a band, lonely and socially anxious Hitori 'Bocchi' Gotou devotes her time to playing the guitar. One day, she meets Nijika Ijichi, who invites her to join Kessoku Band.",
    startDate: "2022-10-09",
    studio: "CloverWorks",
    trailerSite: "youtube",
    trailerId: "4A_X-Dvl0ws",
    nextAiringEpisode: null,
    nextAiringAt: null,
  },
];

const EPISODE_TITLES_BY_SHOW: Record<number, string[]> = {
  16498: [
    "To You, in 2,000 Years: The Fall of Shiganshina, Part 1",
    "That Day: The Fall of Shiganshina, Part 2",
    "A Dim Light Amid Despair: Humanity's Comeback, Part 1",
    "The Night of the Closing Ceremony: Humanity's Comeback, Part 2",
    "First Battle: The Struggle for Trost, Part 1",
    "The World the Girl Saw: The Struggle for Trost, Part 2",
    "Small Blade: The Struggle for Trost, Part 3",
    "I Can Hear His Heartbeat: The Struggle for Trost, Part 4",
    "Whereabouts of His Left Arm: The Struggle for Trost, Part 5",
    "Response: The Struggle for Trost, Part 6",
    "Idol: The Struggle for Trost, Part 7",
    "Wound: The Struggle for Trost, Part 8",
    "Primal Desire: The Struggle for Trost, Part 9",
    "Can't Look into His Eyes Yet: Eve of the Counterattack, Part 1",
    "Special Operations Squad: Eve of the Counterattack, Part 2",
    "What Should Be Done: Eve of the Counterattack, Part 3",
    "Female Titan: The 57th Exterior Scouting Mission, Part 1",
    "Forest of Giant Trees: The 57th Exterior Scouting Mission, Part 2",
    "Bite: The 57th Exterior Scouting Mission, Part 3",
    "Erwin Smith: The 57th Exterior Scouting Mission, Part 4",
    "Crushing Blow: The 57th Exterior Scouting Mission, Part 5",
    "The Defeated: The 57th Exterior Scouting Mission, Part 6",
    "Smile: Assault on Stohess, Part 1",
    "Mercy: Assault on Stohess, Part 2",
    "Wall: Assault on Stohess, Part 3",
  ],
  101922: [
    "Cruelty",
    "Trainer Sakonji Urokodaki",
    "Sabito and Makomo",
    "Final Selection",
    "My Own Steel",
    "Swordsman with a Demon",
    "Muzan Kibutsuji",
    "The Smell of Enchanting Blood",
    "Temari Demon and Arrow Demon",
    "Together Forever",
    "Tsuzumi Mansion",
    "The Boar Bares Its Fangs, Zenitsu Sleeps",
    "Something More Important Than Life",
    "The House with the Wisteria Family Crest",
    "Mount Natagumo",
    "Letting Someone Else Go First",
    "You Must Master a Single Thing",
    "A Forged Bond",
    "Hinokami",
    "Pretend Family",
    "Against Corps Rules",
    "Master of the Mansion",
    "Hashira Meeting",
    "Rehabilitation Training",
    "Tsuguko, Kanao Tsuyuri",
    "New Mission",
  ],
  113415: [
    "Ryomen Sukuna",
    "For Myself",
    "Girl of Steel",
    "Curse Womb Must Die",
    "Curse Womb Must Die -II-",
    "After Rain",
    "Assault",
    "Boredom",
    "Small Fry and Reverse Retribution",
    "Idle Transfiguration",
    "Narrow-minded",
    "To You, Someday",
    "Tomorrow",
    "Kyoto Sister School Exchange Event - Group Battle 0 -",
    "Kyoto Sister School Exchange Event - Group Battle 1 -",
    "Kyoto Sister School Exchange Event - Group Battle 2 -",
    "Kyoto Sister School Exchange Event - Group Battle 3 -",
    "Sage",
    "Black Flash",
    "Nonstandard",
    "Jujutsu Koshien",
    "The Origin of Blind Obedience",
    "The Origin of Blind Obedience - 2 -",
    "Accomplices",
  ],
  154587: [
    "The Journey's End",
    "It Didn't Have to Be Magic...",
    "Killing Magic",
    "The Land Where Souls Rest",
    "Phantoms of the Dead",
    "The Hero of the Village",
    "Like a Fairy Tale",
    "Frieren the Slayer",
    "Aura the Guillotine",
    "A Powerful Mage",
    "Winter in the Northern Lands",
    "A Real Hero",
    "Aversion to One's Own Kind",
    "Privilege of the Young",
    "Smell of Trouble",
    "Long-Lived Friends",
    "Take Care",
    "First-Class Mage Exam",
    "Well-Laid Plans",
    "Necessary Murder",
    "The World of Magic",
    "Future Enemies",
    "Conquering the Labyrinth",
    "Perfect Replicas",
    "Fatal Vulnerability",
    "The Height of Magic",
    "An Era of Humans",
    "It Would Be Embarrassing When We Meet Again",
  ],
  151807: [
    "I'm Used to It",
    "If I Had One More Chance",
    "It's Like a Game",
    "I've Gotta Get Stronger",
    "A Pretty Good Deal",
    "The Real Hunt Begins",
    "Let's See How Far I Can Go",
    "This Is Frustrating",
    "You've Been Hiding Your Skills",
    "What Is This, a Picnic?",
    "A Knight Who Defends an Empty Throne",
    "Arise",
  ],
  142838: [
    "Dog & Chainsaw",
    "Arrival in Tokyo",
    "Meowy's Whereabouts",
    "Rescue",
    "Gun Devil",
    "Kill Denji",
    "The Taste of a Kiss",
    "Gunfire",
    "From Kyoto",
    "Bruised & Battered",
    "Mission Start",
    "Katana vs. Chainsaw",
  ],
};

export function generateEpisodes(anime: AnimeCard, seasonIndex = 1): EpisodeEntry[] {
  const count = anime.episodes ?? 12;
  const list: EpisodeEntry[] = [];
  const titles = EPISODE_TITLES_BY_SHOW[anime.id];

  const total = Math.min(count, 36);
  for (let i = 1; i <= total; i++) {
    const prefix = seasonIndex > 1 ? `S${seasonIndex} ` : "";
    const episodeTitle = titles && titles[i - 1] ? `${prefix}${titles[i - 1]}` : `${prefix}Episode ${i}`;
    list.push({
      number: i,
      title: episodeTitle,
      url: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
      aired: anime.startDate ?? "2024-01-01",
      filler: false,
      recap: false,
    });
  }
  return list;
}
